personal_finance:
  target: dev
  outputs:

    dev:
      type: duckdb
      path: "md:personal_finance"
      threads: 4
      settings:
        motherduck_token: "{{ env_var('MOTHERDUCK_TOKEN') }}"

    ci:
      type: duckdb
      path: "md:personal_finance"
      threads: 2
      settings:
        motherduck_token: "{{ env_var('MOTHERDUCK_TOKEN') }}"

    prod:
      path: "md:personal_finance"
      threads: 4
      settings:
        motherduck_token: "{{ env_var('MOTHERDUCK_TOKEN') }}"
