personal_finance:
  target: dev
  outputs:

    dev:
      type: duckdb
      path: "md:personal_finance?motherduck_token={{ env_var('MOTHERDUCK_TOKEN') }}"
      threads: 4

    ci:
      type: duckdb
      path: "md:personal_finance?motherduck_token={{ env_var('MOTHERDUCK_TOKEN') }}"
      threads: 2

    prod:
      type: duckdb
      path: "md:personal_finance?motherduck_token={{ env_var('MOTHERDUCK_TOKEN') }}"
      threads: 4
